YOLOR:
  # WEIGHT: "./detector_weights/yolor/yolor-csp-crowd-50-epochs/best.pt"
  WEIGHT: "./detector_weights_coco/yolor/yolor/yolor_csp.pt" 
  CFG: "./detector/YOLOR/cfg/yolor_csp.cfg"
  DATASET: detector/YOLOR/data/crowdhuman.yaml # maybe it is needed?

  IMG_SIZE: 640
  SCORE_THRESH: 0.4
  CONF_THRESH: 0.25
  NMS_THRESH: 0.45
  IS_XYWH:  True
  HALF: False
