YOLOV7:
  WEIGHT: "./detector_weights_coco/yolov7/yolov7/yolov7x.pt" 

  # WEIGHT: "./detector_weights/yolov7/yolov7x-crowd-100-epochs/best.pt"

  IMG_SIZE: 640
  SCORE_THRESH: 0.35
  CONF_THRESH: 0.25
  NMS_THRESH: 0.45
  IS_XYWH:  True
  HALF: False
