YOLOV6:
  WEIGHT: "./detector/YOLOV6/weights/yolov6s.pt"

  DATASET: ./detector/YOLOV6/data/coco.yaml
  IMG_SIZE: 640
  SCORE_THRESH: 0.35
  CONF_THRESH: 0.25
  NMS_THRESH: 0.45
  IS_XYWH:  True
  HALF: False
