YOLOV4:
  WEIGHT: "./detector/YOLOV4/models/yolov4.weights"
  CFG: "./detector/YOLOV4/models/yolov4.cfg"
  DATASET: ./detector/YOLOV4/data/coco.yaml
  IMG_SIZE: 640
  SCORE_THRESH: 0.5
  CONF_THRESH: 0.25
  NMS_THRESH: 0.45
  IS_XYWH:  True
  HALF: False
