YOLOV5:
  WEIGHT: "./detector/YOLOV5/weights/crowdhuman_cocotune50e/best.pt"
  # WEIGHT: "./detector/YOLOV5/weights/v6.2/yolov5l.pt"
  
  IMG_SIZE: 640
  SCORE_THRESH: 0.5
  CONF_THRESH: 0.25
  NMS_THRESH: 0.45
  IS_XYWH:  True
