YOLOV5:
  # WEIGHT: "./detector/YOLOV5/weights/v4.0/crowdhuman_yolov5m.pt"
  WEIGHT: "./detector/YOLOV5/weights/v4.0/yolov5s.pt"
  
  IMG_SIZE: 640
  SCORE_THRESH: 0.5
  CONF_THRESH: 0.25
  NMS_THRESH: 0.45
  IS_XYWH:  True
