YOLOR:
  WEIGHT: "./models/yolor/yolor_p6.pt"
  CFG: "./detector/YOLOR/cfg/yolor_p6.cfg"
  DATASET: detector/YOLOR/data/coco.yaml
  IMG_SIZE: 640
  SCORE_THRESH: 0.5
  CONF_THRESH: 0.25
  NMS_THRESH: 0.45
  IS_XYWH:  True
  HALF: False
